language: cpp
dist: xenial
sudo: required

cache: ccache

git:
  submodules: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - software-properties-common
      - g++-7
      - luajit-5.1-dev
      - libzmq3-dev
      - mysql-client-core-5.6
      - mysql-server-5.6
      - mysql-client-5.6
      - luarocks

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

before_script:
  - g++ --version
  - python3 ./tools/price_checker.py
  - sh autogen.sh
  - mysql -u root -e 'create database dspdb_test;'

script:
  - ./configure
  - make
  - sh travis_sql.sh
  - sh travis_lua.sh
